"""
Validation Models - VALIDATOR Groundedness Check Results

This module defines the result format for groundedness validation checks.
Used by VALIDATOR to communicate how well answer claims are supported by sources.

Models:
  1. ClaimVerification - Single claim's grounding status
  2. GroundednessReport - Complete groundedness report with score
"""

from pydantic import BaseModel
from typing import Optional, Literal
from .responses import Source


class ClaimVerification(BaseModel):
    """
    Verification status of a single factual claim in the answer.

    VALIDATOR checks each claim to see if it's supported by provided sources.
    This tracks whether the claim is grounded and what source supports it.

    Attributes:
        claim (str): The factual claim extracted from answer
        is_grounded (bool): Whether this claim is supported by sources
        supporting_source (Optional[Source]): Source data backing this claim (if grounded)
        reason (str): Explanation of grounding decision
    """
    claim: str  # The factual claim from answer
    is_grounded: bool  # Supported by sources
    supporting_source: Optional[Source] = None  # Which source backs this claim (if grounded)
    reason: str  # Explanation of grounding verdict


class GroundednessReport(BaseModel):
    """
    Complete groundedness validation report for an answer.

    Generated by VALIDATOR after checking all claims in answer against sources.
    Used to determine if HITL review is needed.

    Scoring:
      Score = (grounded_claims / total_claims)

    Verdicts:
      - "pass": Score >= GROUNDEDNESS_WARN_THRESHOLD (default 0.85)
        → Answer is confident, HITL not needed
      - "warn": Score >= GROUNDEDNESS_TRIPWIRE_THRESHOLD (default 0.70)
        → Answer is marginal, human review may improve it
      - "fail": Score < GROUNDEDNESS_TRIPWIRE_THRESHOLD (default 0.70)
        → Answer is low confidence, HITL required (tripwire triggered)

    Attributes:
        score (float): Overall groundedness score (0.0-1.0)
        claim_verifications (list[ClaimVerification]): Per-claim verification details
        ungrounded_claims (list[str]): List of claims lacking source support
        verdict (Literal): Assessment level (pass/warn/fail)
        recommendation (str): Human-readable guidance for next steps
    """
    score: float  # Groundedness percentage (0.0-1.0)
    claim_verifications: list[ClaimVerification] = []  # Per-claim breakdown
    ungrounded_claims: list[str] = []  # Claims without source support
    verdict: Literal["pass", "warn", "fail"]  # Assessment verdict
    recommendation: str  # Guidance for next action
